vim.g.python3_host_prog = vim.fn.exepath("python3")
require("config.lazy")
require("config.packadds")
require("config.autocmds")
require("config.maps")
require("config.options")
require("config.diagnostic")
require("config.colorscheme")
require("config.terminal")
